artifacts_root: artifacts


data_ingestion: 
  root_dir: /home/akanksha/Desktop/CNN/cnnClassifier/artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/cat-dog-data.zip
  local_data_file: /home/akanksha/Desktop/CNN/cnnClassifier/artifacts/data_ingestion/data.zip
  unzip_dir: /home/akanksha/Desktop/CNN/cnnClassifier/artifacts/data_ingestion